#include "init_sprite.h"

struct skin *init_skin()
{
    struct skin *to_return = malloc(sizeof(struct skin));
	SDL_Surface *a = SDL_LoadBMP("img/batiments/drapeau/face_dos.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
	to_return->drapeauBlancFace_dos = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/faceGauche.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancFaceGauche = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/gauche.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancGauche = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/gaucheFace.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancGaucheFace = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/gaucheDos.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancGaucheDos = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/dosGauche.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancDosGauche = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/dosDroite.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancDosDroite = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/droite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancDroite = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/droiteDos.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancDroiteDos = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/droiteFace.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancDroiteFace = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/batiments/drapeau/faceDroite.bmp");
	SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format, 255, 255, 255));
	a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->drapeauBlancFaceDroite = SDL_CreateTextureFromSurface(renderer, a);
	a = SDL_LoadBMP("img/homme/fantassin/dosRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosDroiteRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoDrRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosDroiteM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoDrMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosDroiteM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoDrMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosDroiteM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoDrMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosDroiteM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoDrMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosDroiteM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoDrMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteDosRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrDoRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteDosM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrDoMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteDosM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrDoMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteDosM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrDoMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteDosM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrDoMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteDosM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrDoMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteFaceRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrFaRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteFaceM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrFaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteFaceM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrFaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteFaceM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrFaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteFaceM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrFaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/droiteFaceM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDrFaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceDroiteRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaDrRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceDroiteM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaDrMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceDroiteM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaDrMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceDroiteM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaDrMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceDroiteM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaDrMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceDroiteM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaDrMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceGaucheRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaGaRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceGaucheM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaGaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceGaucheM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaGaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceGaucheM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaGaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceGaucheM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaGaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/faceGaucheM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaFaGaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheFaceRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaFaRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheFaceM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaFaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheFaceM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaFaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheFaceM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaFaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheFaceM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaFaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheFaceM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaFaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheDosRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaDoRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheDosM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaDoMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheDosM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaDoMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheDosM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaDoMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheDosM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaDoMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/gaucheDosM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaGaDoMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosGaucheRien.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoGaRien = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosGaucheM1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoGaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosGaucheM2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoGaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosGaucheM3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoGaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosGaucheM4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoGaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/fantassin/dosGaucheM5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoFaDoGaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/dos1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDoMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/dos2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDoMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/dos3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDoMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/dos4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDoMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/dos5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDoMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteDos1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDdMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteDos2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDdMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteDos3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDdMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteDos4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDdMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteDos5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDdMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droite1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDrMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droite2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDrMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droite3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDrMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droite4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDrMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droite5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDrMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteFace1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDfMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteFace2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDfMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteFace3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDfMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteFace4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDfMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/droiteFace5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArDfMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/face1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArFaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/face2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArFaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/face3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArFaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/face4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArFaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/face5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArFaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheFace1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGfMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheFace2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGfMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheFace3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGfMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheFace4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGfMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheFace5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGfMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gauche1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGaMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gauche2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGaMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gauche3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGaMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gauche4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGaMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gauche5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGaMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheDos1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGdMa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheDos2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGdMa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheDos3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGdMa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheDos4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGdMa4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/homme/archer/gaucheDos5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->hoArGdMa5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/eau/ship1/haut.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ship1haut = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/nature/nouriture/fruit.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->fruit = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/nature/nouriture/legume.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->legume = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/nature/arbre1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->arbre1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);

    a = SDL_LoadBMP("img/batiments/chateau/face.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauFace = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/faceGauche.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauFaceGauche = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/gaucheFace.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauGaucheFace = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/droite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauGauche = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/gaucheDos.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauGaucheDos = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/dosGauche.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauDosGauche = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/dos.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauDos = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/dosDroite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauDosDroite = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/droiteDos.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauDroiteDos = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/droite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauDroite = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/droiteFace.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauDroiteFace = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/chateau/faceDroite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->chateauFaceDroite = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    
    a = SDL_LoadBMP("img/batiments/tour/face.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourFace = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/faceDroite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourFaceDroite = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/droiteFace.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourDroiteFace = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/droite.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourDroite = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/dos.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourDos = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/gauche.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourGauche = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/gaucheFace.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourGaucheFace = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/batiments/tour/faceGauche.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->tourFaceGauche = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    return to_return;
}

struct textures *init_textures()
{
    struct textures *to_return = malloc(sizeof(struct textures));
    SDL_Surface *a = SDL_LoadBMP("img/textures/he1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/sa1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/sa2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/sa3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ea1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ea1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ea2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ea2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ea3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ea3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/te1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->te1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/te2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->te2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/te3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->te3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ne1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ne1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ne2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ne2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ne3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ne3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/gr1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->gr1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/gr2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->gr2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/bl1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->bl1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/bl2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->bl2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/bl3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->bl3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/fond.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->fond = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    return to_return;
}

struct gui_sprite *init_gui_sprite()
{
    struct gui_sprite *to_return = malloc(sizeof(struct gui_sprite));
    SDL_Surface *a = SDL_LoadBMP("img/gui/croix.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->croix = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/croix2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->croix_inverse = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
     a = SDL_LoadBMP("img/gui/demarcation.bmp");
     SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
     a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->demarcation = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/plus.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->plus = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/moins.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->moins = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/elipse.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->elipse = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/selected.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->selecteur = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/main_menu.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->main_menu_button = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/pressed_main_menu.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->pressed_main_menu_button = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/no_sound.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->pressed_sound_button = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/sound.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sound_button = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);

    a = SDL_LoadBMP("img/gui/buttons/lines.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->lines = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/square.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->square = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/triangle.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->triangle = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/gui/buttons/splitted.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->splited_lines = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    return to_return;
}

struct img *init_img()
{
    struct img *ret = malloc(sizeof(struct img));
    ret->t = init_textures();
    ret->s = init_skin();
    ret->g = init_gui_sprite();
    return ret;
}
