#include "init_img.h"

struct textures * textures;
SDL_Renderer *renderer;
SDL_Window *window;

struct textures *init_textures()
{
    struct textures *to_return = malloc(sizeof(struct textures));
    SDL_Surface *a = SDL_LoadBMP("img/textures/he1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he4.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he4 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/he5.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->he5 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/sa1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sa1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/sa2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sa2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/sa3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->sa3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ea1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ea1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ea2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ea2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ea3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ea3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/te1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->te1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/te2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->te2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/te3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->te3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ne1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ne1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ne2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ne2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/ne3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->ne3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/gr1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->gr1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/gr2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->gr2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/bl1.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->bl1 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/bl2.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->bl2 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/bl3.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->bl3 = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/select.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->select = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    a = SDL_LoadBMP("img/textures/menu_textures.bmp");
    SDL_SetColorKey(a, SDL_SCANCODE_Y, SDL_MapRGB(a->format,255,255,255));
    a = SDL_ConvertSurfaceFormat(a, SDL_GetWindowPixelFormat(window), 0);
    to_return->menu_textures = SDL_CreateTextureFromSurface(renderer, a);
    SDL_FreeSurface(a);
    return to_return;
}
